version: '3'

services:
  api:
    build:
      target: make_app
    ports:
      - '3000:3000'
  redis:
    ports:
      - '6379:6379'
  db:
    image: postgres:alpine
    ports:
      - '5432:5432'
