import { IBioData } from '../interfaces/Bio.interfaces';

export const data: IBioData = {
    profile: {
        descriptions: [
            `Experienced Full-Stack Engineer with 8+ years of expertise in designing, developing, and maintaining scalable web applications and services. Proficient in both frontend and backend development, with a strong command of JavaScript (TypeScript, React, Node.js) and Java. Skilled in building robust systems, integrating APIs, and optimizing performance across the entire Software Development Life Cycle (SDLC).`,
            'Java: 6+ years, Node.js: 5+ years, Frontend (React, Vue.js, Angular): 7+ years, PostgreSQL: 6+ years, MongoDB: 4+ years',
        ],
    },
    history: [
        {
            entity: '@sberbank',
            link: 'https://www.sberbank.ru',
            state: 'Product Owner | Team Leadership (13 members)',
            period_start: '2025/01',
            period_end: '',
            region: 'Russia, Moscow',
            todo: [
                'CI/CD Pipeline Optimization: Designed and implemented a robust CI/CD pipeline using the internal banking DOT platform, streamlining development and deployment processes.',
                'Job Aggregation Interface: Developed a unified interface for aggregating and managing all DPM jobs, enhancing operational efficiency.',
                'Infrastructure Setup: Configured and deployed 2 SynGx (Nginx) instances per environment with load balancers, ensuring high availability and scalability.',
                'Security Integration: Implemented OIDC (IAM Proxy) authentication for each environment, improving security and access control.',
                'Firewall Configuration: Set up Sowa firewall to securely handle requests from public environments.',
                'Dynamic Content Platform: Built a Java + React (Single SPA) application featuring a dynamic homepage that renders content based on user permissions.',
                'Platform Integration: Established a seamless process for onboarding third-party applications onto the platform, enabling scalability and interoperability.',
                'Compliance & Quality Assurance: Ensured all applications meet bank requirements, including integrations with OCA (Authorization Service), Logging, and Audit systems. Successfully passed all Quality Gates, ensuring compliance with security and performance standards.',
            ],
        },
        {
            entity: '@sberbank',
            link: 'https://www.sberbank.ru',
            state: 'full-stack engineer',
            period_start: '2022/10',
            period_end: '2024/12',
            region: 'Russia, Moscow',
            todo: [
                'API Development: Designed and implemented APIs using OData, RESTful APIs, and Kafka for asynchronous communication.',
                'Mobile Development: Utilized Capacitor for cross-platform mobile app development, ensuring compliance with bank requirements.',
                'Team Leadership: Mentored new employees, organized and chaired weekly team meetings, and participated in recruitment processes.',
                'Agile Collaboration: Worked closely with solution architects, developers, designers, and business analysts to design, develop, test, and deploy applications in an agile environment.',
                'Backlog Management: Detailing and planning of the current backlog, ensuring timely delivery of features and improvements.',
                'Backend Development: Built robust backend systems using Java and Node.js.',
                'Frontend Development: Developed user interfaces using React, ensuring a seamless user experience.',
                'SCIM Specification Implementation: Developed a Java application implementing SCIM specification, transforming traffic into SOAP and deploying it to production.',
                'File Parsing & Text Indexing: Created a Java application for parsing files and generating text indexes.',
                'Bank Share Registry: Built an application for managing and storing the bank’s share registry.',
                'Budget Commitment Order Registry: Developed a system for storing and managing budget commitment orders.',
                'Start Page & Auxiliary Services: Maintained and enhanced the application’s start page and supporting services.',
                'Kafka Integration: Used Kafka for log transmission to external systems and asynchronous communication in a notification service (@900).',
                'Mobile App Development: Enhanced the platform’s mobile application to meet bank-specific requirements.',
            ],
        },
        {
            entity: '@pinpointer',
            link: 'https://www.pinpointer.se',
            state: 'full-stack engineer',
            period_start: '2021/2',
            period_end: '2022/10',
            region: 'Sweden (remotely)',
            todo: [
                'Technology Stack: Java (Spring Boot), React, RESTful APIs, GraphQL, RabbitMQ, Mongodb.',
                'Mobile Development: Utilized Capacitor for cross-platform mobile app development.',
                'Team Leadership: Mentored new employees, organized and chaired weekly team meetings, and participated in recruitment processes.',
                'Agile Collaboration: Worked in agile/scrum teams, collaborating with solution architects, developers, designers, and business analysts to design, develop, test, and deploy applications.',
                'Backlog Management: Detailing and planning of the current backlog, ensuring timely delivery of features and improvements.',
                'Integrated an internal logistics system with document management workflows.',
                'Integrated a specialized truck routing system to calculate and optimize permissible routes.',
                'Microservices Migration: Played a key role in scaling the team by breaking down a monolithic application into microservices, doubling the team size.',
            ],
        },
        {
            entity: '@alternativa',
            link: 'https://agenta.online/',
            state: 'full-stack engineer',
            period_start: '2020',
            period_end: '2021/2',
            region: 'Russia, Kazan',
            todo: [
                'Technology Stack: Java, PostgreSQL, Vue.js, RESTful APIs, RabbitMQ.',
                'Application Optimization: Optimized the application for rapid development and seamless integration with insurance companies, enabling 10+ integrations per year.',
                'Environment Setup: Configured and maintained development and testing environments.',
                'Data Visualization: Developed interactive WebGL-based graphs for data visualization.',
                'System Integration: Integrated the application with Power BI and the customer’s accounting system.',
                'Security Implementation: Deployed and configured Keycloak for secure authentication and authorization.',
                'CI/CD Pipeline: Built and maintained a Bitbucket pipeline for efficient deployment and continuous integration.',
                'Microservices Architecture: Designed and implemented 12+ microservices, improving scalability and maintainability.',
            ],
        },
        {
            entity: '@redtaxi',
            link: 'https://www.linkedin.com/company/redtaxilb/about/',
            state: 'full-stack engineer',
            period_start: '2020',
            period_end: '2020/3',
            region: 'Lebanon (remotely)',
            todo: ['Stack: postgres + express', 'API: RestApi', 'Integration application with payment system', 'Setup test/development environment'],
        },
        {
            entity: '@mobishop',
            link: 'https://www.linkedin.com/company/mobishop/about/',
            state: 'javascript engineer',
            period_start: '2019',
            period_end: '2020',
            region: 'Russia, Moscow',
            todo: [
                'Stack: MEAN',
                'API: RestApi',
                'Mentoring for new employees',
                "Creating of endpoints adapted for the customer's systems for the current API",
                'Optimization shop performance',
                'Optimization database performance',
            ],
        },
        {
            entity: '@cleanup',
            link: 'https://cleanup.one',
            state: 'javascript engineer',
            period_start: '2018',
            period_end: '2019',
            region: 'Russia, Kazan',
            todo: ['Stack: bootstrap + express', 'API: RestApi', 'Development application for customer needs', 'Close cooperation with the marketing department'],
        },
        {
            entity: '@freelance',
            link: '',
            state: 'full-stack engineer',
            period_start: '2016',
            period_end: '2018',
            region: 'Russia, Kazan',
            todo: ['Creating of a CRM system', 'Scraping of information from the web sites', 'Creating of a plain web sites', 'Creating reports from the database'],
        },
        {
            entity: '@csp',
            link: 'https://цсп-рт.рф',
            state: 'system administrator',
            period_start: '2013',
            period_end: '2015',
            region: 'Russia, Kazan',
            todo: [
                'Creating a news site in several languages',
                'Maintenance of the video surveillance portal for sports facilities of the republic',
                'Maintenance of 150 corporate computers',
                'Maintenance of 5 physical servers',
            ],
        },
        {
            entity: 'other',
            link: '',
            state: 'other projects',
            period_start: '2008',
            period_end: '2013',
            region: 'Russia, Kazan',
            todo: [
                'Developed scripts for automating armor upgrade processes in Lineage 2 using ACTools.',
                'Created team event scripts for monitoring ally HP levels and automating healing in Lineage 2.',
                'Enhanced and studied JAVA through modifications of the l2j game server.',
                'Performed packet-level hacking of game servers.',
                'Modified game clients to render hitboxes (wallhack).',
                'Designed scripts to manage weapon spray patterns and recoil in multiple games.',
            ],
        },
    ],
    skills: {
        languages: ['TypeScript', 'Python', 'JAVA', 'Groovy'],
        Databases: ['Mongodb', 'Postgres'],
        'Web Frameworks': ['Angular', 'Vue', 'React', 'Capacitor'],
        'Backend Frameworks': ['Express', 'Nestjs', 'Spring'],
        'Testing tools': ['Jest', 'Puppeteer', 'JUnit'],
        Communication: ['RabbitMQ', 'RestApi', 'Web Socket', 'GraphQL'],
        Other: ['Linux', 'Docker', 'Gitlab CI', 'Bitbucket CI', 'Elasticsearch (ELK)', 'Web scraping', 'Flow', 'Eslint', 'Ansible', 'Helm', 'Jenkins', 'Kubernetes', 'Openshift'],
    },
    education: [
        {
            entity: 'Tisbi, Hight school',
            period_start: '2022',
            period_end: '2025',
            region: 'Russia, Kazan',
            todo: [
                'Pursuing a second higher education in Applied Informatics through remote learning, building on my existing academic background.',
                'Gaining advanced knowledge in software development, data analysis, and IT systems design to complement my practical experience.',
                'Focused on modern technologies, programming paradigms, and best practices in the field of information technology.',
            ],
        },
        {
            entity: 'Kazan (Volga) Federal University, Hight school',
            period_start: '2012',
            period_end: '2018',
            region: 'Russia, Kazan',
            todo: ['2 years of study. Applied Informatics. Studied JAVA.', 'After 2 years of study, I transferred to the law faculty.'],
        },
    ],
    certificates: [
        {
            title: 'Cambly',
            link: 'http://www.cambly.com/en/certificate/verify/ca9527ad',
        },
        {
            title: 'GOF & GRASP',
            link: 'https://www.icloud.com/iclouddrive/0KU6Ub8JDVOESk3dyNXskmXfg#gof_grasp',
        },
        {
            title: 'Enterprise Patterns',
            link: 'https://www.icloud.com/iclouddrive/005qATrj3omHA15DKIUibB-zw#ep',
        },
    ],
};
